### ISSUE TITLE
Nominatim-docker - Problem Viewbox

### ISSUE THREAD

**Issue by galina2000** [cartography/nominatim-docker#1]
Поиск в ограничительной рамке (используя параметр Viewbox) не выполняется. Установила в nominatim-docker карту Пензенской области. Выполняю запрос поиска объектов, находящихся в городе Пенза. Для этого указываю параметр viewbox. Но результаты поиска содержат не только объекты г. Пенза, но и объекты Пензенской области. Т.е фильтрации результатов с учетом viewbox не выполняется. Возможно неправильно указала параметр viewbox для г.Пензы?

**Comment by winsento** [comment]
Ок, я посмотрю.

**Comment by winsento** [comment]
@galina2000  это проблема не Docker контейнера, а самого Nominatim. Написал им тикет, следить можно тут https://github.com/twain47/Nominatim/issues/452
